### ISSUE TITLE
The URL given in help does not match the repository URL

### ISSUE THREAD

**Issue by musicfuel** [metasys-server/powershell-metasysrestclient#37]
https://github.com/metasys-server/powershell-metasysrestclient/blob/ec498315e7e809f85403def5aa76bc5463456120/MetasysRestClient/Invoke-MetasysMethod.psm1#L110

I tried using this for more information and got a 404. I believe `powershell-metasysrestapi` should instead be `powershell-metasysrestclient`. I ended up finding the right repo through a search which matched this line of code.

**Comment by michaelgwelch** [comment]
sorry I missed the notifications on all my feature requests.
